project:
  type: book
  output-dir: docs

book:
  title: "Theory of Electromagnetic Methods"
  subtitle: "Lecture Notes"
  author: "Ralph-Uwe Börner"
  date: today
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
      - intro.qmd
      - fourier.qmd
      - maxwell.qmd
      - pde.qmd
      - mtfields.qmd
      - Differential_Operators_Sympy.ipynb
      - semisphere.ipynb
    - part: "Summary"
      chapters: 
        - summary.qmd
    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/geophysical-journal-international

format:
  html:
    theme: cosmo
    crossref:
      chapters: true
      eq-prefix: ""
    code-fold: true
    code-summary: "Show the code"
#  pdf:
#    documentclass: scrreprt
#    papersize: a4

editor: visual

