project:
  type: book
  output-dir: docs

book:
  title: "Theory of Electromagnetic Methods"
  subtitle: "Lecture Notes"
  author: "Ralph-Uwe Börner"
  date: today
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
      - preface.qmd
      - intro.qmd
      - fourier.qmd
    - part: "Maxwell's equations"
      chapters:
      - maxwell.qmd
      - pde.qmd
      - mtfields.qmd
    - part: "Dipole induction"
      chapters:
      - potentials.qmd
      - timedomain_fullspace.qmd
      - halfspace.qmd
      - explicit.qmd
      - hankel_transform.qmd
      - layered_halfspace.qmd
      - timedomain_halfspace.qmd
    - part: "Exercises"
      chapters:
      - python_problems.qmd
    - part: "Summary"
      chapters: 
        - summary.qmd
    - references.qmd

bibliography: references/references.bib
csl: https://www.zotero.org/styles/geophysical-journal-international

format:
  html:
    theme: lumen
    crossref:
      chapters: true
      eq-prefix: ""
    code-fold: true
    code-summary: "Show the code"
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            loader: {
              load: ['[tex]/physics']
            },
            tex: {
              packages: {'[+]': ['physics']}
            }
          };
          </script>
#  pdf:
#    documentclass: scrreprt
#    papersize: a4

editor: visual

