---
jupyter: python3
---

## Prerequisites {.unnumbered}

Here are the lecture notes for the 2024 module covering the **Theory of Electromagnetic Methods.** These notes are tailored for Master's students of Geophysics and Geoinformatics at the [Institute of Geophysics and Geoinformatics, TU Bergakademie Freiberg](https://tu-freiberg.de/geophysik).

You can access all the materials on the GitHub repository <https://github.com/ruboerner/ThEM>.

Enjoy studying!

## Background

This course targets Master's students in their second semester, with a recommended understanding of fundamental geoelectromagnetic applications. Additionally, prior completion of the Theoretical Physics - Electrodynamics course is strongly advised as a prerequisite for this lecture.

## Code

The website's course material includes sections with embedded Python code.

You can easily copy the code and execute it in a compatible Python runtime environment.

For an optimal experience, we recommend installing Python via [*miniconda*](https://docs.anaconda.com/free/miniconda/index.html).

Moreover, you have the freedom to explore your own concepts and delve deeper into the course content by creating your personalized Jupyter notebooks. You can utilize any of the following platforms:

-   [Visual Studio Code](https://code.visualstudio.com/)
-   [Jupyterlab](https://jupyter.org)
-   [Quarto](https://quarto.org)
-   [mystMD](https://mystmd.org).

Working with Jupyter Notebooks in Visual Studio Code is [exceptionally straightforward](https://code.visualstudio.com/docs/datascience/jupyter-notebooks).

## Recommended Reading

@ward1988electromagnetic

## License

This material is licensed under a Creative Commons License.