---
title: "Electromagnetic fields"
---

In electromagnetics we deal with the following *fields*:

-   electric field $\mathbf E$, unit $V / m$
-   magnetic field $\mathbf H$, unit $A / m$
-   electric displacement field $\mathbf D$, unit $As / m^2$
-   magnetic flux density $\mathbf B$, unit $Vs / m^2$
-   electic current density field $\mathbf J$, unit $A / m^2$

All considered fields are functions of *space* $\mathbf r$ and *time* $t$, i.e.,

$$
\mathbf e(\mathbf r, t), \mathbf h(\mathbf r, t), \mathbf d(\mathbf r, t), \mathbf b(\mathbf r, t),
\mathbf j(\mathbf r, t)
$$ {#eq-fields-time} or a function of the *angular frequency* $\omega = 2 \pi f$, such that $$
\mathbf E(\mathbf r, \omega), \mathbf H(\mathbf r, \omega), \mathbf D(\mathbf r, \omega), \mathbf B(\mathbf r, \omega),
\mathbf J(\mathbf r, \omega).
$$ {#eq-fields-frequency} In the latter case, the time dependency of any field $\mathbf F$ is always defined as $$ 
\mathbf F(\mathbf r, \omega) = \mathbf F_0(\mathbf r) e^{i \omega t},
$$ and the quantity of interest is $\mathbf F_0$.

**Convention:** Upper case letters: Frequency domain, lower case letters: Time domain.

See @eq-fourier for a definition of the Fourier transform.

## Material properties

In electromagnetics we have the following material properties:

-   electrical conductivity $\sigma$
-   dielectrical permittivity $\varepsilon$
-   magnetic permeability $\mu$.

In the context of geo-electromagnetics, these parameters are associated with particular rock properties which are studied in *petrophysics*.

## Simplifications

As we know from theroretical physics, the relations between the fields and the associated parameters are very general and allow, e.g., strong frequency-dependency or non-linearities.

In geo-electromagnetics, however, we can allow for a few simplifications.

All rock parameters are supposed to be

-   linear with respect to the fields
-   stationary, and
-   isotropic.

We will see later that anisotropy is a quite general rock property which needs to be considered in the interpretation of geo-electromagnetic field data.

Moreover, we will first study the general properties of the EM induction in a uniform full-space by neglecting any spatial inhomogeneities of the parameters.
