---
title: "Maxwell's Equations"
---

The EM fields @eq-fields-time are solutions of *Maxwell's equations*

$$
\curl \mathbf h - \partial_t \mathbf d   = \mathbf j
$$ {#eq-ampere}

$$
\curl \mathbf e + \partial_t \mathbf b  = \mathbf 0
$$ {#eq-faraday}

$$
\divergence \mathbf b  = 0
$$ {#eq-gauss-b}

$$
\divergence \mathbf d  = \rho_E
$$ {#eq-gauss-d}

In the form presented here, Maxwell's equations are an **uncoupled set of ordinary differential equations**.

## Constitutive equations

The goal is to couple these equations. This can be achieved with the use of the **constitutive equations**, which are

$$
\begin{align}
\mathbf d & = \varepsilon \mathbf e \\
\mathbf b & = \mu \mathbf h
\end{align}
$$ {#eq-constitutive-equations}

Generally, the linear parameters $\varepsilon, \mu$ are rank-2 **tensors** represented as 3-by-3 matrices.

## Ohm's law

In an electrically conductive medium, any electric field gives rise to an electric current. This current is expressed by its *current density* as

$$
\mathbf j = \sigma \mathbf e,
$$ {#eq-ohms-law}

where $\sigma$ is a rank-2 tensor.

This tensor can be represented in matrix form as

$$
\sigma =   \begin{pmatrix}    \sigma_{11} & \sigma_{12} & \sigma_{13} \\    \sigma_{21} & \sigma_{22} & \sigma_{23} \\    \sigma_{31} & \sigma_{32} & \sigma_{33}   \end{pmatrix}.
$$

Tensors like introduced here cause *anisotropy*, i.e., the material properties have different values across different spatial directions.

A typical observation would be the deviation of the induced current density from the direction of the driving electric field.

### Remarks about anisotropy

The rank-2 tensor of electrical conductivity $\tilde\sigma$ may be represented in matrix form as

$$
  \hat\sigma = 
  \begin{pmatrix}
    \sigma_{11} & \sigma_{12} & \sigma_{13} \\
    \sigma_{21} & \sigma_{22} & \sigma_{23} \\
    \sigma_{31} & \sigma_{32} & \sigma_{33} 
  \end{pmatrix}.
$$

Any real symmetric (n-by-n) matrix $A$ can be diagonalized (principal axis theorem), such that

$$
D_A = S^\top A S  
$$

is a diagonal matrix, and $S$ is an orthogonal matrix.

Interpreting the matrix $A$ as a linear map in $\mathbb {R} ^3$, then the matrix $S$ can be thought of as a transformation to the new basis.
Between the old and new coordinates there is the relation $\mathbf {x}=S \boldsymbol {\xi }$.
The action of the matrix $A$ in the new coordinate system is taken over by the diagonal matrix $D_{A}$.

After transformation of the tensor in diagonal form, we have
$$ 
  \tilde\sigma = 
  \begin{pmatrix}
    \sigma_{xx} & 0 & 0 \\
    0 & \sigma_{yy} & 0 \\
    0 & 0 & \sigma_{zz} 
  \end{pmatrix}.
$$

If $\sigma_{xx} = \sigma_{yy} = \sigma_{zz} = \sigma$, then
$$
  \tilde\sigma = \sigma
  \begin{pmatrix}
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & 0 & 1 
  \end{pmatrix} = \sigma.
$$
In this case, the conductivity does not depend on the spatial direction and hence is labelled _isotropic_.

