---
title: "Partial Differential Equations"
jupyter: python3
---

As we have seen, Maxwell's equations can be coupled using the constitutive equations and Ohm's law.

After Fourier transform w.r.t. time $t$, but in a slightly different notation, we obtain $$
\begin{bmatrix}
\nabla \times & -i\omega\varepsilon \mathbf I \\
+i\omega\mu_0 \mathbf I & \nabla \times
\end{bmatrix}
\begin{bmatrix}
\mathbf H \\ \mathbf E
\end{bmatrix} = 
\begin{bmatrix}
\mathbf J \\ \mathbf 0
\end{bmatrix}
$$

$$
\begin{bmatrix}
\nabla \cdot & 0 \\
0 & \nabla \cdot
\end{bmatrix}
\begin{bmatrix}
\mathbf B \\ \mathbf D
\end{bmatrix} = 
\begin{bmatrix}
0 \\ \rho_E
\end{bmatrix}
$$ Note that the sources of the fields--- $\mathbf J$ and $\rho_E$ ---always appear on the right-hand side of the equations. $\mathbf I$ denotes the 3-by-3 identity matrix.

By elimination of one field, e.g., the magnetic field, we are able to cast the system of first-order ODEs into a *second-order partial differential equation* (PDE).

As an alternative, a complete solution of the Maxwell system, i.e., $\mathbf E$ and $\mathbf H$, can be obtained by taking the solution of one of the two vector valued equations and applying the curl.

We refer to the following *types* of PDEs:

-   elliptic
-   parabolic
-   hyperbolic

::: {.callout-note appearance="simple" icon="false" collapse="true"}
## Self-study questions

-   What are the characteristic features of the three types of PDEs?
-   What typical (geophysical) applications are associated with the above types?
:::

## The curl-curl equation

We first eliminate one field from the set of Maxwell's equations by applying the *curl operator* ($\nabla \times$) to one of the equations, i.e., Faraday's law.

This results in a second-order PDE because we differentiate twice with respect to spatial coordinates.

::: {.callout-tip collapse="true"}
$$
\begin{align}
\nabla \times \mathbf e  & = -\partial_t \mathbf b \\
\nabla \times \nabla \times \mathbf e & = \nabla \times (-\partial_t \mathbf b) \\
  & = -\nabla \times (\partial_t \mathbf b) \\
  & = -\partial_t\nabla \times  \mathbf b \\
  & = -\partial_t\nabla \times ( \mu \mathbf h) \\
  & = -\partial_t \mu \nabla \times \mathbf h \\
  & = -\mu \partial_t \nabla \times \mathbf h \\
  & = -\mu \partial_t (\mathbf j + \partial_t \mathbf d) \\
  & = -\mu \partial_t (\sigma \mathbf e + \partial_t \mathbf d) \\
  & -\mu \partial_t (\sigma \mathbf e + \partial_t \varepsilon \mathbf e) \\
  & = -\mu \partial_t \sigma \mathbf e -\mu \partial^2_{tt} \varepsilon \mathbf e \\
  & = -\mu \sigma \partial_t \mathbf e -\mu \varepsilon \partial^2_{tt} \mathbf e
\end{align}
$$
:::

Finally, we obtain the **curl-curl equation** for the electric field $\mathbf e$ as $$
\nabla \times \nabla \times \mathbf e  +\mu \sigma \partial_t \mathbf e + \mu \varepsilon \partial^2_{tt} \mathbf e = \mathbf 0.
$$ {#eq-curlcurl}

This is a second-order PDE with first- and second-order time derivatives.

Note that you obtain a similar PDE for the magnetic field $\mathbf h$ if you apply the steps outlined above to Ampere's law.

Often, a slightly different form of @eq-curlcurl is used.

The following identity is useful for any vector field $\mathbf f$: $$
\nabla \times \nabla \times \mathbf f = \nabla \nabla \cdot \mathbf f - \nabla^2 \mathbf f 
$$ {#eq-vector-identity}

This equation is useful, e.g., when $\nabla \cdot \mathbf f = 0$. In this case the curl-curl operator can be replaced by $-\nabla^2$, the *vector Laplace operator* defined over a vector field.

::: callout-warning
The vector Laplacian is similar to the scalar Laplacian. The scalar Laplacian applies to a scalar field and returns a scalar quantity, whereas the vector Laplacian applies to a vector field and returns a vector quantity.

In Cartesian coordinates, the returned vector field is equal to the vector field of the scalar Laplacian applied to each vector component.
:::

Under which conditions can we switch from the *curl-curl* to the *Laplace* operator? Clearly, the term $\nabla \nabla \cdot \mathbf f$ must vanish (or its contribution must be negligible).

### Decay of free charges

When the electric field $\mathbf e$ is considered, we are faced with the following problem: Under which conditions $\nabla \cdot \mathbf e$ becomes negligible small?

The answer should be clear: When there are no free charges present in the considered domain, there is no associated electric field.

Recall, that in a uniform dielectric medium there holds *Gauß' s law* for electric charges

$$
\nabla \cdot \mathbf e = \frac{\rho_E}{\varepsilon},
$$

where $\rho_E$ is the volume charge density and $\varepsilon = \varepsilon_r \varepsilon_0$ is the permittivity.

Let's find out how to solve the problem.

We want to show that $\nabla \cdot \mathbf e \approx 0$ for some time $t>0$. As long as $t \le 0$, there is a certain charge density $\rho_E(t)$ concentrated at, e.g., the origin of a uniform fullspace.

We apply the divergence operator to Ampere's law:

$$
\begin{align}
\nabla \cdot \nabla \times \mathbf h & = \nabla \cdot \mathbf j + \partial_t \nabla \cdot \mathbf d \\
& = 0
\end{align}
$$

With $$
\nabla \cdot \mathbf d = \rho_E \\
\nabla \cdot \mathbf j = \nabla \cdot (\sigma \mathbf e) = \nabla\sigma \cdot \mathbf e + \sigma \nabla \cdot \mathbf e \\
\sigma \nabla \cdot \mathbf e = \sigma \frac{\rho_E}{\varepsilon}
$$ we obtain an initial-value problem for the charge density

$$
\frac{\sigma}{\varepsilon} \rho_E + \dot{\rho_E} = 0.
$$

Its solution is

$$
\rho_E(t) = \rho_E(0) \exp\left({-\frac{\sigma}{\varepsilon}t}\right).
$$ {#eq-decay}

#### Numerical experiment

To study the decay of a free charge denoted by an electrical charge density, we define as initial condition for $t=0$ that $\rho_E(0) = 1~A\cdot s\cdot m^{-3}$ .

Further, the conductivity of the uniform fullspace is 0.01 S/m.

We plot the function @eq-decay for a very small time window:

```{python}
#| code-fold: true
import numpy as np
import matplotlib.pyplot as plt

sigma_n = 0.01
epsilon_n = 8.854e-12

def rho(t):
  return np.exp(-sigma_n/epsilon_n * t)

t_n = np.logspace(-13, -7, num=71, endpoint=True)

plt.semilogx(t_n, rho(t_n))
plt.xlabel('t in s')
plt.ylabel(r'$\rho_E(t)/\rho_E(0)$')
plt.show()
```

By visual inspection, after approx. 10 ns the volume charge density has dropped to zero.

Let's be more precise:

We can calculate the time at which the charge density decays to a given fraction of its initial value, e.g., to 1 ppm.

```{python}
from sympy import *

t, sigma, epsilon, rho0 = symbols('t sigma epsilon rho_0', real=True)
rhoE = symbols('rho_E')

expr = rhoE - rho0 * exp(-sigma / epsilon * t)

tt = solve(expr, t)
tt[0]
```

We find that the time $t$ at which a certain fraction of the initial charge density is obtained, can be calculated using

$$
\hat{t} = \frac{\epsilon }{\sigma}\log{\left(\frac{\rho_{0}}{\rho_{E}} \right)} = -\frac{\epsilon }{\sigma}\log{\left(\frac{\rho_{E}}{\rho_{0}} \right)}
$$

```{python}
tstar = -epsilon_n / sigma_n * np.log(1e-6)
```

With the values given above, the charge density drops to 1 ppm of its initial value after `{python} '{0:.2e}'.format(tstar)` seconds.

## The Telegraph equation

By virtue of @eq-vector-identity we can cast the curl-curl equation @eq-curlcurl into the telegraph equation of induction, such that

$$
-\nabla^2 \mathbf e + \mu \sigma \partial_t \mathbf e + \mu \varepsilon \partial^2_{tt} \mathbf e = \mathbf 0.
$$ {#eq-telegraph-full}

::: callout-note
Note that the same PDE can be derived for the magnetic field!
:::

Eq. @eq-telegraph-full and @eq-curlcurl are second-order linear PDEs with at most second-order time derivatives. Hence, they describe wave phenomena.

::: callout-note
A second-order, linear, constant-coefficient PDE for $u$ takes the general form

$$
A u_{xx} + 2 B u_{xy} + C u_{yy} + D u_x + E u_y + F u + G = 0
$$

This PDE is classified as being

-   *parabolic,* when $B^2 - AC = 0$

-   *hyperbolic*, when $B^2 - AC > 0$

-   *elliptic*, when $B^2 - AC < 0$.

In our case, $x$ plays the role of any spatial variable, and $t$ plays the role of $y$.

Hence, for @eq-telegraph-full, $A=-1$, $E=\mu\sigma$, $C=\mu\varepsilon$, and the remaining coefficients are zero.

Checks:

$B^2 - AC = 0 - (-1 \cdot \mu\varepsilon) > 0$ $\to$ PDE is *hyperbolic*.

$B^2 - AC = 0 - (-1 \cdot 0) = 0$ $\to$ PDE is *parabolic*

For the elliptic PDE there are no time derivatives, we can therefore let $x$ and $y$ take their roles as Cartesian coordinates.

So, with $A = C = -1$,

$B^2 - AC = 0 - (-1 \cdot -1) < 0$ $\to$ PDE is elliptic.
:::
